### ISSUE TITLE
首页 404

### ISSUE THREAD

**Issue by kxxoling** [RicterZ/AnimeReminder#12]
启动的是 ar-django 分支，syncdb 后打开首页是 404。。。

**Comment by RicterZ** [comment]
404 中应该有可以访问的地址，好像是 `/rest/`。 
这个现在主要还是利用 Django REST Framework 来调试的。

**Comment by kxxoling** [comment]
添加订阅也是通过 API？没有互动页面吗？

**Comment by RicterZ** [comment]
我的想法是前端用 AngularJS 或者 backbone，直接调用 API 即可，这样手机的 App 和 Web 可以用一套 API。

**Comment by kxxoling** [comment]
这样的话，直接根据请求头去调用渲染引擎就好了。话说，这两个分支分别是做什么的？为什么默认分支不是 master？

**Comment by RicterZ** [comment]
master 是之前（刚学 python 的时候）用 web.py 写的..数据库设计以及代码都惨不忍睹 /w\

**Comment by kxxoling** [comment]
。。。

**Comment by RicterZ** [comment]
QWQ

**Comment by kxxoling** [comment]
这几天被 Django 各版本以及插件之间的兼容性恶心死了，我又回归 Flask 的怀抱了～ 刚刚创建了一个新项目 https://github.com/kxxoling/horus 可惜还是没有什么 ACG 相关的好想法。
动漫订阅我自己不是很用的着，重点还是怎么获取资源，待会儿看看凤凰字幕网站的接口再想想。
