### ISSUE TITLE
模块：B站动漫集数获取

### ISSUE THREAD

**Issue by RicterZ** [RicterZ/AnimeReminder#3]
传入sp id，解析得到集数。
分析http://www.bilibili.tv/video/bgm_calendar.html 所有番剧，找到规律。
比如：
野良神，URL为`http://www.bilibili.tv/sppage/bangumi-18199-1.html`
中二病也要谈恋爱，URL为`http://www.bilibili.tv/sppage/bangumi-5691-705-1.html`

然后返回野良神是11集，中二病是11集（目前）

**Comment by Madimo** [comment]
你这是前端不动后端重写么 。。

**Comment by RicterZ** [comment]
差不多

**Comment by RicterZ** [comment]
解析《日常》：http://www.bilibili.tv/sp/日常 的时候报错，spid：782
注意有的最后一集并不是最后，要判断。
